---
title: "NYC Restaurant Inspections"
author: 'Zanis Fang, UID: ZF2213'
date: "10/29/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(plotly)

instacart_raw <- p8105.datasets::instacart

instacart_raw %>%
	filter(reordered == 1) %>%
	group_by(product_name) %>% 
	summarize(n_reordered = n()) %>% 
	top_n(10) %>%
	ggplot(aes(x = reorder(product_name, n_reordered), y = n_reordered)) +
	  geom_point()

instacart_raw %>% 
	distinct(order_id, order_hour_of_day, order_dow) %>% 
	ggplot(aes(order_hour_of_day)) + 
	  geom_density()

instacart_raw %>% 
	plot_ly(x = ~order_hour_of_day, color = ~as.factor(order_dow), type = "histogram")

instacart_raw %>% 
	group_by(order_number) %>% 
	summarize(total_orders = n()) %>% 
	ggplot(aes(x = order_number, y = total_orders)) +
	  geom_point()


instacart_raw %>% 
	distinct(order_number, order_hour_of_day) %>% 
	ggplot(aes(y = order_hour_of_day, x = as.factor(order_number))) +
	  geom_boxplot()

instacart_raw %>% 
	distinct(order_number, order_dow) %>% 
	ggplot(aes(y = order_dow, x = as.factor(order_number))) +
	  geom_boxplot()

```

```{r boxplot_frequency_vs_quantity}

# order frequency and number of items in an order
instacart_raw %>% 
	group_by(order_id) %>% 
	mutate(items_ordered = n()) %>%
	distinct(items_ordered, days_since_prior_order) %>% 
	ggplot(aes(y = log(items_ordered), x = as.factor(days_since_prior_order))) +
	  geom_boxplot()

# plotly	
instacart_raw %>% 
	group_by(order_id) %>% 
	mutate(items_ordered = n()) %>% 
	distinct(items_ordered, days_since_prior_order) %>% 
	plot_ly(x = ~as.factor(days_since_prior_order),
					y = ~log(items_ordered),
					type = "box")
```

```{r histogram_density_plot_order_frequency}
instacart_raw %>% 
	distinct(order_id, days_since_prior_order) %>% 
	ggplot(aes(x = days_since_prior_order)) +
	  geom_density()

instacart_raw %>% 
	distinct(order_id, days_since_prior_order) %>% 
	plot_ly(x = ~days_since_prior_order, type = "histogram")
	
	
```

```{r scatter_orders_vs_order_num}
# trends over order_number
instacart_raw %>% 
	group_by(order_number, aisle) %>% 
	summarize(n_order = n()) %>% 
	ggplot(aes(y = log(n_order), x = order_number, color = aisle)) +
	  geom_point(show.legend = FALSE) +
	  geom_smooth(show.legend = FALSE)

# take a view of several aisle
instacart_raw %>% 
	group_by(order_number, aisle) %>% 
	summarize(n_order = n()) %>%
	ungroup() %>% 
	filter(aisle %in% sample(unique(aisle), 5)) %>% 
	ggplot(aes(y = log(n_order), x = order_number)) +
	  geom_point(aes(color = aisle)) +
	  facet_grid(. ~ aisle) +
	  geom_smooth(method = lm)

# plotly
set.seed(67)
instacart_raw %>% 
	group_by(order_number) %>% 
	summarize(n_order = n()) %>% 
	ggplot(aes(x = order_number, y = log(n_order))) +
	  geom_point()

set.seed(50)
instacart_raw %>% 
	group_by(order_number) %>% 
	mutate(n_order = n()) %>%
	group_by(order_number, aisle, n_order) %>%
	summarize(aisle_n_order = n()) %>%
  ungroup() %>% 
	mutate(order_mix = paste(order_number, n_order, sep = "/")) %>%
	select(aisle_n_order, aisle, order_mix) %>%
  spread(key = order_mix, value = aisle_n_order, fill = NA) %>%
	gather(key = order_mix, value = aisle_n_order, "10/60216":"99/250") %>%
	separate(order_mix, into = c("order_number", "n_order"), sep = "/") %>%
	mutate(order_number = as.numeric(order_number),
				 n_order = as.numeric(n_order)) %>%
	mutate(aisle_n_order = ifelse(!is.na(aisle_n_order),
																			 log(aisle_n_order / n_order),
																			 -10)) %>% 
  filter(aisle %in% sample(unique(aisle), 134)) %>% 
	plot_ly(x = ~order_number, y = ~aisle_n_order, type = "scatter", mode = "markers",
					color = ~aisle,
					text = ~aisle
					)
	
```	

```{r practice_map_lists}
nest_instacart <- instacart_raw %>% 
	group_by(order_number, aisle) %>% 
	summarize(n_order = n()) %>% 
	ungroup() %>%
	nest(c(n_order, order_number))



instacart_lm <- function(df) {
	lm(log(n_order) ~ order_number, data = df)
}

lm_instacart <- map(nest_instacart$data, function(x) instacart_lm(x)$coefficients[2])

nest_instacart %>%
	mutate(beta1 = unlist(lm_instacart)) %>% 
	arrange(beta1) %>% View
```

```{r bar_frequently_ordered_with_cereal}
# which ordered most frequently with cereal

with_cereal <- instacart_raw %>% 
	group_by(aisle) %>% 
	mutate(n_aisle = n()) %>%
	group_by(order_id) %>% 
	# if cereal in aisle
	mutate(has_cereal = "cereal" %in% aisle) %>%
	filter(has_cereal == TRUE) %>% 
	group_by(aisle, n_aisle) %>% 
	summarize(ratio_with_cereal = n()) %>%
	mutate(ratio_with_cereal = ratio_with_cereal / n_aisle) %>% 
	ungroup()

top_cereal <- rbind(
  with_cereal %>%
	  top_n(11, ratio_with_cereal) %>% 
	  mutate(is_top = "top"),
  with_cereal %>%
	  top_n(-10, ratio_with_cereal) %>% 
	  mutate(is_top = "bottom")
  ) %>% 
	filter(aisle != "cereal")

top_cereal %>% 
	ggplot(aes(x = reorder(aisle, rank(ratio_with_cereal)), y = ratio_with_cereal)) +
	  geom_bar(stat = "identity")

# plotly	  
top_cereal %>% 
	plot_ly(x = ~reorder(aisle, rank(ratio_with_cereal)),
					y = ~ratio_with_cereal,
					type = "bar",
					color = ~ is_top)

```

